/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProGApp;

import java.awt.Color;
import java.io.FileNotFoundException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.bson.Document;
import org.json.JSONObject;

/**
 *
 * @author DUONG.BuiQuang
 */
public class MainApp extends javax.swing.JFrame {

  /**
   * Creates new form MainApp
   */
  
  DefaultListModel listModel = new DefaultListModel();
  DefaultListModel listDone = new DefaultListModel();

  int todoId;
  
  public MainApp() throws FileNotFoundException {
    
    initComponents();
    var data = FileService.readFile();
    sayHi.setText("Hi, " + (String) data.get("username"));
    todoId = (int) data.get("todoId");
    var todoWorks = Connection.getMyTodos(todoId);
    todoWorks.forEach(todoWork -> listModel.addElement(todoWork));
    var doneWorks = Connection.getMyDoneTodos(todoId);
    doneWorks.forEach(todoWork -> listDone.addElement(todoWork));
    todoList.setModel(listModel);
    doneList.setModel(listDone);
    btnEdit.setEnabled(false);
    btnDelete.setEnabled(false);
    
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    btnEdit = new javax.swing.JButton();
    btnDelete = new javax.swing.JButton();
    btnFinish = new javax.swing.JButton();
    btnAdd = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    textField = new javax.swing.JTextField();
    jScrollPane3 = new javax.swing.JScrollPane();
    todoList = new javax.swing.JList<>();
    jScrollPane2 = new javax.swing.JScrollPane();
    doneList = new javax.swing.JList<>();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    sayHi = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setBackground(new java.awt.Color(255, 204, 204));
    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    btnEdit.setBackground(new java.awt.Color(51, 255, 204));
    btnEdit.setText("EDIT");
    btnEdit.setBorder(null);
    btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnEditMouseClicked(evt);
      }
    });
    btnEdit.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnEditActionPerformed(evt);
      }
    });
    jPanel1.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 279, 133, 55));

    btnDelete.setBackground(new java.awt.Color(255, 51, 0));
    btnDelete.setText("DELETE");
    btnDelete.setBorder(null);
    btnDelete.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnDeleteActionPerformed(evt);
      }
    });
    jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 340, 126, 55));

    btnFinish.setBackground(new java.awt.Color(255, 255, 0));
    btnFinish.setText("FINISH");
    btnFinish.setBorder(null);
    btnFinish.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnFinishActionPerformed(evt);
      }
    });
    jPanel1.add(btnFinish, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 340, 133, 55));

    btnAdd.setBackground(new java.awt.Color(0, 255, 51));
    btnAdd.setText("ADD");
    btnAdd.setBorder(null);
    btnAdd.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnAddActionPerformed(evt);
      }
    });
    jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 279, 126, 55));

    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Add your today's tasks");
    jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 45, 258, 30));

    textField.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusGained(java.awt.event.FocusEvent evt) {
        textFieldFocusGained(evt);
      }
    });
    jPanel1.add(textField, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 101, 258, 40));

    todoList.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusGained(java.awt.event.FocusEvent evt) {
        todoListFocusGained(evt);
      }
      public void focusLost(java.awt.event.FocusEvent evt) {
        todoListFocusLost(evt);
      }
    });
    todoList.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        todoListMouseClicked(evt);
      }
    });
    jScrollPane3.setViewportView(todoList);

    jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 250, 250));

    jScrollPane2.setViewportView(doneList);

    jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 250, 200));

    jLabel2.setText("Done");
    jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, -1, -1));

    jLabel3.setForeground(new java.awt.Color(255, 51, 51));
    jLabel3.setText("Logout");
    jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mousePressed(java.awt.event.MouseEvent evt) {
        jLabel3MousePressed(evt);
      }
    });
    jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 60, 40));
    jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 120, -1));

    sayHi.setForeground(new java.awt.Color(0, 204, 204));
    sayHi.setText("jLabel5");
    jPanel1.add(sayHi, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 100, 30));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
    // TODO add your handling code here:
    String content = textField.getText();
    if(content.equals("")) {
      JOptionPane.showMessageDialog(null, "Field can not be empty.");
    }
    else {
      listModel.addElement(content);
      JOptionPane.showMessageDialog(null, "add todo successfully.");
      Document doc = new Document("todo_work", content).append("user_id", todoId).append("created_at", LocalDate.now()).append("is_finished", false);
      Connection.addTodo(doc);
    }
    textField.setText(null);
  }//GEN-LAST:event_btnAddActionPerformed

  private void textFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldFocusGained
    // TODO add your handling code here:
    btnDelete.setEnabled(false);
    btnEdit.setEnabled(false);
    btnAdd.setEnabled(true);
  }//GEN-LAST:event_textFieldFocusGained

  private void btnEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseClicked
    // TODO add your handling code here:
    String preValue = todoList.getSelectedValue();
    var content = JOptionPane.showInputDialog("update your todo", preValue);
    int index = todoList.getSelectedIndex();
    listModel.setElementAt(content, index);
    Connection.updateTodo(preValue, content);
  }//GEN-LAST:event_btnEditMouseClicked

  private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnEditActionPerformed

  private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
    // TODO add your handling code here:
    int index = todoList.getSelectedIndex();
    String value = todoList.getSelectedValue();
    int reply = JOptionPane.showConfirmDialog(null, "Are you sure?", "Delete", JOptionPane.YES_NO_OPTION);
    if(reply == JOptionPane.YES_OPTION) {
      listModel.removeElementAt(index);
      JOptionPane.showMessageDialog(null, "Delete todo successfully");
      Connection.deleteTodo(value);
    }
    else {
      btnDelete.setEnabled(false);
      btnEdit.setEnabled(false);
      btnAdd.setEnabled(true);
    }
  }//GEN-LAST:event_btnDeleteActionPerformed

  private void btnFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinishActionPerformed
    // TODO add your handling code here:
    int index = todoList.getSelectedIndex();
    if(index > -1) {  
      String value = todoList.getSelectedValue();
      listModel.removeElementAt(index);
      listDone.addElement(value);
      Connection.updateFinishTask(value);
    }
  }//GEN-LAST:event_btnFinishActionPerformed

  private void todoListFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_todoListFocusGained
    // TODO add your handling code here:
    btnFinish.setEnabled(true);
  }//GEN-LAST:event_todoListFocusGained

  private void todoListFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_todoListFocusLost
    // TODO add your handling code here:
//    btnFinish.setEnabled(false);
  }//GEN-LAST:event_todoListFocusLost

  private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
    try {
      // TODO add your handling code here:
      FileService.deleteFile();
      var loginForm = new Login();
      loginForm.setVisible(true);
      loginForm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
      this.dispose();
    } catch (FileNotFoundException ex) {
      Logger.getLogger(MainApp.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_jLabel3MousePressed

  private void todoListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_todoListMouseClicked
    // TODO add your handling code here:
    if(todoList.getSelectedIndex() > -1) {
      btnEdit.setEnabled(true);
      btnDelete.setEnabled(true);
    }
  }//GEN-LAST:event_todoListMouseClicked

  
  /**
   * @param args the command line arguments
   */
 
  
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        try {
          new MainApp().setVisible(true);
        } catch (FileNotFoundException ex) {
          Logger.getLogger(MainApp.class.getName()).log(Level.SEVERE, null, ex);
        }
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnAdd;
  private javax.swing.JButton btnDelete;
  private javax.swing.JButton btnEdit;
  private javax.swing.JButton btnFinish;
  private javax.swing.JList<String> doneList;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JScrollPane jScrollPane3;
  private javax.swing.JLabel sayHi;
  private javax.swing.JTextField textField;
  private javax.swing.JList<String> todoList;
  // End of variables declaration//GEN-END:variables

}
